name: Build & Deploy pipeline

on:
  push:
    branches:
      - main
      - k8s-example

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Install required
        run: sudo apt-get update -y 1> /dev/null && sudo apt install awscli -y 1> /dev/null
      - name: Login to ECR
        run: aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 310008400154.dkr.ecr.eu-west-1.amazonaws.com
      - name: Build
        run: |
          IMAGE_VERSION=$GITHUB_SHA;
          docker build --no-cache . -t 310008400154.dkr.ecr.eu-west-1.amazonaws.com/vponoiko_test_com-mgmt-ecr-django-ai-site:$IMAGE_VERSION --platform linux/amd64 ;
          docker push 310008400154.dkr.ecr.eu-west-1.amazonaws.com/vponoiko_test_com-mgmt-ecr-django-ai-site:$IMAGE_VERSION
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Install AWS cli
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
      - name: Install kubectl
        run: |
          KUBECTL_VERSION=$(curl -L -s https://dl.k8s.io/release/stable.txt)
          sudo wget -q -O /usr/local/bin/kubectl https://dl.k8s.io/release/$KUBECTL_VERSION/bin/linux/amd64/kubectl
          sudo chmod +x /usr/local/bin/kubectl
      - name: Install helm
        run: |
          # HELM_VERSION=$(curl -Ls https://github.com/helm/helm/releases | grep 'href="/helm/helm/releases/tag/v3.[0-9]*.[0-9]*\"' | sed -E 's/.*\/helm\/helm\/releases\/tag\/(v[0-9\.]+)".*/\1/g' | head -1)
          HELM_VERSION="v3.13.3"
          sudo wget -q https://get.helm.sh/helm-$HELM_VERSION-linux-amd64.tar.gz -O - | tar -xzO linux-amd64/helm > helm
          sudo mv helm /usr/local/bin/helm
          sudo chmod +x /usr/local/bin/helm
      - name: Fetch kubeconfig
        run: |
          aws eks update-kubeconfig --region eu-west-1 --name ${{ secrets.EKS_CLUSTER_NAME }}
          export KUBECONFIG=$HOME/.kube/config
          kubectl version
      - name: Deploy | Helm upgrade
        run:
           helm upgrade django-ai-site-release k8s/chart/ --namespace django-ai-site -f k8s/chart/values-example.yaml --set image.tag=$GITHUB_SHA
